[phases.setup]
nixPkgs = ["php81", "php81Extensions.intl", "php81Extensions.mbstring", "php81Packages.composer"]

[phases.install]
cmds = ["composer install"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "cd public && php -S 0.0.0.0:$PORT"