[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y libzip-dev",
    "docker-php-ext-install zip"
]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "php spark key:generate --force",
    "chmod -R 755 writable"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"